### ISSUE TITLE
Built-in Shader Encoding Issues

### ISSUE THREAD

**Issue by xezno** [xezno/mocha#19]
(From Discord): users with non-Unicode default encoding (such as shift jis) currently experience the following engine crash on startup:

![image](https://user-images.githubusercontent.com/12881812/213614388-ed436f4e-9525-4c91-9369-71b7d974a6d8.png)

Theories:
- The string is being encoded in shift jis but the shader compiler (glslang) expects utf-8
- The shader compiler expects to convert from the user's locale to utf-8, but is passed a utf-8 string instead
- Something else

I am not at all experienced with character encoding so I'm not sure what could be causing this right now.

**Comment by MuffinTastic** [comment]
So after a closer look I'm now about 90% sure this isn't an encoding error. I led with that assumption because I've been burned too many times by other programs on things relating to text, my mistake. It not being an encoding error is made more likely by the fact that the issue remained even since setting both system locale/encoding to UTF-16 and the display language to English.

Anyways, with that out of the way I did some more digging online for the `0xCD` byte that keeps appearing (appearing as `ﾍ` in that screenshot) and found some other people with similar problems, and it all came down to badly terminated C strings (or other sorts of strings mistakenly interpreted as C strings) and [the CRT pre-initializing newly allocated memory on the debug heap to that value](https://learn.microsoft.com/en-us/visualstudio/debugger/crt-debug-heap-details#:~:text=New%20objects%20(0xCD)%20New%20objects%20are%20filled%20with%200xCD%20when%20they%20are%20allocated.). Consider that `vTexCoord` is 9 characters long, then there's 7 of that magic `0xCD` byte, and then the last character is a tab - to me, this looks suspiciously similar to padding for byte alignment.

Since this had to do with the debug heap, on a hunch I set it to compile in release mode, and lo and behold, the shaders compile, and the engine moves on all the way until the main loop. Can't say if the shaders work yet, I've got some other (probably?) unrelated issues to work through first.

I've stepped through the execution of the shader loading code line by line, keeping an eye on local variables, and at no point does it get corrupted as far as I can tell, certainly not within Mocha itself. My hunch is that this is some kind of glslang issue, but for all I know it could be specific to my pc. I'll be wiping my environment completely and starting over tomorrow just to be sure.

**Comment by xezno** [comment]
> the CRT pre-initializing newly allocated memory on the debug heap to that value

This checks out, when compiling a release build these won't get filled, but whatever memory it's allocating might just happen to contain or be filled with `0x00`, which would null-terminate the string when strcpying into the allocated memory.

This does indeed look like it's probably an issue within glslang itself. It might therefore be best, both to fix this bug & for workflow reasons, to switch away from inline shaders like this and instead just compile these shaders directly as .spv files, which should negate this issue entirely.

**Comment by xezno** [comment]
Turns out this was caused by a bad compile or something, and that recompiling glslang specifically seems to have fixed it. I'm going to close this for now but if anyone else comes across this issue, please let me know.

![image](https://user-images.githubusercontent.com/12881812/213870932-408652f8-16cb-44bc-98e7-14d3bb69ce96.png)
