### ISSUE TITLE
How to install???

### ISSUE THREAD

**Issue by BatterySand** [xezno/mocha#29]
How do I install this

**Comment by peter-r-g** [comment]
Read the [pre-requisites](https://github.com/xezno/mocha#instructions) and [instructions](https://github.com/xezno/mocha#instructions).

**Comment by BatterySand** [comment]
It doesn’t work

**Comment by peter-r-g** [comment]
Need more info, provide any errors and warnings you get as well as your specs.

**Comment by BatterySand** [comment]
No.

**Comment by gumby-cmyk** [comment]
Bruh

**Comment by Xenthio** [comment]
no

**Comment by Xenthio** [comment]
hello mocha discord commits channel!!!!!!!!!!!a

**Comment by Xenthio** [comment]
issue channel i meant issue

**Comment by xezno** [comment]
As peter-r-g said you can check the build instructions or the readme or wait until nightly binaries get set up in the future.

Closing this as wontfix because you've made it clear you're not going to provide any additional information. If you have any issues with building please open a new issue with extra context and we will be glad to assist you.
